// Generated by gen_census.py -- do not edit.
// Drive HD0..HD15 from tx_word while we own the bus; high-Z otherwise.
assign HD0          = hd_drive ? tx_word[ 0] : 1'bz;
assign HD1          = hd_drive ? tx_word[ 1] : 1'bz;
assign HD2          = hd_drive ? tx_word[ 2] : 1'bz;
assign HD3          = hd_drive ? tx_word[ 3] : 1'bz;
assign HD4          = hd_drive ? tx_word[ 4] : 1'bz;
assign HD5          = hd_drive ? tx_word[ 5] : 1'bz;
assign HD6          = hd_drive ? tx_word[ 6] : 1'bz;
assign HD7          = hd_drive ? tx_word[ 7] : 1'bz;
assign HD8          = hd_drive ? tx_word[ 8] : 1'bz;
assign HD9          = hd_drive ? tx_word[ 9] : 1'bz;
assign HD10         = hd_drive ? tx_word[10] : 1'bz;
assign HD11         = hd_drive ? tx_word[11] : 1'bz;
assign HD12         = hd_drive ? tx_word[12] : 1'bz;
assign HD13         = hd_drive ? tx_word[13] : 1'bz;
assign HD14         = hd_drive ? tx_word[14] : 1'bz;
assign HD15         = hd_drive ? tx_word[15] : 1'bz;
