// Generated by gen_census.py -- do not edit.
// hd_bus[0..22] = HD0..HD22 (HD17 unavailable, tied 0); hd_bus[23] = HD31.
wire [23:0] hd_bus = {
    HD31        ,  // [23] HD31
    HD22        ,  // [22] HD22
    HD21        ,  // [21] HD21
    HD20        ,  // [20] HD20
    HD19        ,  // [19] HD19
    HD18        ,  // [18] HD18
    1'b0        ,  // [17] HD17
    HD16        ,  // [16] HD16
    HD15        ,  // [15] HD15
    HD14        ,  // [14] HD14
    HD13        ,  // [13] HD13
    HD12        ,  // [12] HD12
    HD11        ,  // [11] HD11
    HD10        ,  // [10] HD10
    HD9         ,  // [ 9] HD9
    HD8         ,  // [ 8] HD8
    HD7         ,  // [ 7] HD7
    HD6         ,  // [ 6] HD6
    HD5         ,  // [ 5] HD5
    HD4         ,  // [ 4] HD4
    HD3         ,  // [ 3] HD3
    HD2         ,  // [ 2] HD2
    HD1         ,  // [ 1] HD1
    HD0           // [ 0] HD0
};
