// Generated by gen_census.py -- do not edit.
// Body of drive_hd(w): put a 24-bit word on the HD lines.
tb_obs[  0] = w[ 0];   // HD0
tb_obs[  1] = w[ 1];   // HD1
tb_obs[ 11] = w[ 2];   // HD2
tb_obs[ 15] = w[ 3];   // HD3
tb_obs[ 17] = w[ 4];   // HD4
tb_obs[ 18] = w[ 5];   // HD5
tb_obs[ 19] = w[ 6];   // HD6
tb_obs[ 20] = w[ 7];   // HD7
tb_obs[ 21] = w[ 8];   // HD8
tb_obs[ 22] = w[ 9];   // HD9
tb_obs[  2] = w[10];   // HD10
tb_obs[  3] = w[11];   // HD11
tb_obs[  4] = w[12];   // HD12
tb_obs[  5] = w[13];   // HD13
tb_obs[  6] = w[14];   // HD14
tb_obs[  7] = w[15];   // HD15
tb_obs[  8] = w[16];   // HD16
tb_obs[  9] = w[18];   // HD18
tb_obs[ 10] = w[19];   // HD19
tb_obs[ 12] = w[20];   // HD20
tb_obs[ 13] = w[21];   // HD21
tb_obs[ 14] = w[22];   // HD22
tb_obs[ 16] = w[23];   // HD31
