// Generated by gen_census.py -- do not edit.
// ISP header pins 27 and 28 are switched to ground so the header has a
// reference for the UART on J19; everything else stays off.
assign j_gnd_11   = 1'b0;
assign j_gnd_21   = 1'b0;
assign j_gnd_26   = 1'b0;
assign j_gnd_27   = 1'b1;
assign j_gnd_28   = 1'b1;
assign j_vcc_04   = 1'b0;
assign j_vcc_20   = 1'b0;
assign j_vcc_22   = 1'b0;
assign j_vcc_24   = 1'b0;
assign j_vpp_24   = 1'b0;
assign j_vpp_26   = 1'b0;
