// Generated by gen_census.py -- do not edit.
wire [15:0] hd_read = {
    obs_net[  7],   // HD15
    obs_net[  6],   // HD14
    obs_net[  5],   // HD13
    obs_net[  4],   // HD12
    obs_net[  3],   // HD11
    obs_net[  2],   // HD10
    obs_net[ 22],   // HD9
    obs_net[ 21],   // HD8
    obs_net[ 20],   // HD7
    obs_net[ 19],   // HD6
    obs_net[ 18],   // HD5
    obs_net[ 17],   // HD4
    obs_net[ 15],   // HD3
    obs_net[ 11],   // HD2
    obs_net[  1],   // HD1
    obs_net[  0]   // HD0
};
