// Generated by gen_census.py -- do not edit.
localparam integer NPINS  = 113;
localparam integer NBYTES = 15;

// obs[i] corresponds to index i in pinmap.json.
wire [NPINS-1:0] obs = {
    j_28          ,  // [112] F5    ISP:J28
    j_27          ,  // [111] F3    ISP:J27
    j_26          ,  // [110] F4    ISP:J26
    j_25          ,  // [109] E3    ISP:J25
    j_24          ,  // [108] D3    ISP:J24
    j_23          ,  // [107] C2    ISP:J23
    j_22          ,  // [106] C3    ISP:J22
    j_21          ,  // [105] E4    ISP:J21
    j_20          ,  // [104] E12   ISP:J20
    j_18          ,  // [103] D14   ISP:J18
    j_17          ,  // [102] E15   ISP:J17
    j_16          ,  // [101] F12   ISP:J16
    j_14          ,  // [100] H13   ISP:J14
    j_13          ,  // [ 99] H14   ISP:J13
    j_12          ,  // [ 98] K14   ISP:J12
    j_11          ,  // [ 97] J12   ISP:J11
    j_10          ,  // [ 96] J11   ISP:J10
    j_09          ,  // [ 95] M14   ISP:J09
    j_08          ,  // [ 94] M4    ISP:J08
    j_07          ,  // [ 93] M5    ISP:J07
    j_06          ,  // [ 92] M3    ISP:J06
    j_05          ,  // [ 91] L3    ISP:J05
    j_04          ,  // [ 90] J3    ISP:J04
    j_03          ,  // [ 89] H4    ISP:J03
    j_02          ,  // [ 88] H3    ISP:J02
    zif_48        ,  // [ 87] T12   ZIF48
    zif_47        ,  // [ 86] R12   ZIF47
    zif_46        ,  // [ 85] T14   ZIF46
    zif_45        ,  // [ 84] R14   ZIF45
    zif_44        ,  // [ 83] T15   ZIF44
    zif_43        ,  // [ 82] R16   ZIF43
    zif_42        ,  // [ 81] P15   ZIF42
    zif_41        ,  // [ 80] N16   ZIF41
    zif_40        ,  // [ 79] N14   ZIF40
    zif_39        ,  // [ 78] K16   ZIF39
    zif_38        ,  // [ 77] J16   ZIF38
    zif_37        ,  // [ 76] J14   ZIF37
    zif_36        ,  // [ 75] J1    ZIF36
    zif_35        ,  // [ 74] H2    ZIF35
    zif_34        ,  // [ 73] H1    ZIF34
    zif_33        ,  // [ 72] K2    ZIF33
    zif_32        ,  // [ 71] M2    ZIF32
    zif_31        ,  // [ 70] M1    ZIF31
    zif_30        ,  // [ 69] N1    ZIF30
    zif_29        ,  // [ 68] N3    ZIF29
    zif_28        ,  // [ 67] P1    ZIF28
    zif_27        ,  // [ 66] P2    ZIF27
    zif_26        ,  // [ 65] R1    ZIF26
    zif_25        ,  // [ 64] R2    ZIF25
    zif_24        ,  // [ 63] A3    ZIF24
    zif_23        ,  // [ 62] B3    ZIF23
    zif_22        ,  // [ 61] A2    ZIF22
    zif_21        ,  // [ 60] B2    ZIF21
    zif_20        ,  // [ 59] B1    ZIF20
    zif_19        ,  // [ 58] C1    ZIF19
    zif_18        ,  // [ 57] D1    ZIF18
    zif_17        ,  // [ 56] E1    ZIF17
    zif_16        ,  // [ 55] E2    ZIF16
    zif_15        ,  // [ 54] F1    ZIF15
    zif_14        ,  // [ 53] G1    ZIF14
    zif_13        ,  // [ 52] F2    ZIF13
    zif_12        ,  // [ 51] H16   ZIF12
    zif_11        ,  // [ 50] H15   ZIF11
    zif_10        ,  // [ 49] G16   ZIF10
    zif_09        ,  // [ 48] G14   ZIF09
    zif_08        ,  // [ 47] F16   ZIF08
    zif_07        ,  // [ 46] F15   ZIF07
    zif_06        ,  // [ 45] E16   ZIF06
    zif_05        ,  // [ 44] D16   ZIF05
    zif_04        ,  // [ 43] C16   ZIF04
    zif_03        ,  // [ 42] C15   ZIF03
    zif_02        ,  // [ 41] B16   ZIF02
    zif_01        ,  // [ 40] B15   ZIF01
    unknown_c4    ,  // [ 39] C4    ? ro5 ?
    tms           ,  // [ 38] A15   TMS(nc)
    tdo           ,  // [ 37] E14   TDO(nc)
    tdi           ,  // [ 36] C12   TDI(nc)
    tck           ,  // [ 35] C14   TCK(nc)
    m1            ,  // [ 34] N11   M1
    m0            ,  // [ 33] T11   M0
    cpu_p13       ,  // [ 32] R5    Cpu: 13
    HTVLD         ,  // [ 31] C11   Cpu: 52
    HTREQ         ,  // [ 30] C9    Cpu: 54
    HTRDY         ,  // [ 29] T4    Cpu: 18
    HTCLK         ,  // [ 28] E8    Cpu: 56
    HTACK         ,  // [ 27] C8    Cpu: 55
    HRVLD         ,  // [ 26] L7    Cpu: 14
    HRCLK         ,  // [ 25] R7    Cpu: 10
    HRACT         ,  // [ 24] T5    Cpu: 11
    HD9           ,  // [ 23] D5    Cpu: 25
    HD8           ,  // [ 22] D8    Cpu: 24
    HD7           ,  // [ 21] M9    Cpu:23
    HD6           ,  // [ 20] P10   Cpu: 22
    HD5           ,  // [ 19] N12   Cpu: 21
    HD4           ,  // [ 18] P12   Cpu: 20
    HD31          ,  // [ 17] T10   Cpu: 51
    HD3           ,  // [ 16] N5    Cpu: 19
    HD22          ,  // [ 15] B5    Cpu: 38
    HD21          ,  // [ 14] A4    Cpu: 37
    HD20          ,  // [ 13] C7    Cpu: 36
    HD2           ,  // [ 12] C10   Cpu: 53
    HD19          ,  // [ 11] R11   Cpu: 35
    HD18          ,  // [ 10] R3    Cpu: 34
    HD17          ,  // [  9] T2    Cpu: 33
    HD16          ,  // [  8] P13   Cpu: 32
    HD15          ,  // [  7] A7    Cpu: 31
    HD14          ,  // [  6] E7    Cpu: 30
    HD13          ,  // [  5] E6    Cpu: 29
    HD12          ,  // [  4] C6    Cpu: 28
    HD11          ,  // [  3] D6    Cpu: 27
    HD10          ,  // [  2] C5    Cpu: 26
    HD1           ,  // [  1] P5    Cpu: 17
    HD0             // [  0] L8    Cpu: 15
};
