// Generated by gen_census.py -- do not edit.
// obs[i] corresponds to index i in pinmap.json.
wire [NPINS-1:0] obs = {
    j_25          ,  // [101] E3    ISP:J25
    j_24          ,  // [100] D3    ISP:J24
    j_23          ,  // [ 99] C2    ISP:J23
    j_22          ,  // [ 98] C3    ISP:J22
    j_20          ,  // [ 97] E12   ISP:J20
    j_19          ,  // [ 96] E13   ISP:J19
    j_18          ,  // [ 95] D14   ISP:J18
    j_17          ,  // [ 94] E15   ISP:J17
    j_16          ,  // [ 93] F12   ISP:J16
    j_14          ,  // [ 92] H13   ISP:J14
    j_13          ,  // [ 91] H14   ISP:J13
    j_12          ,  // [ 90] K14   ISP:J12
    j_10          ,  // [ 89] J11   ISP:J10
    j_09          ,  // [ 88] M14   ISP:J09
    j_07          ,  // [ 87] M5    ISP:J07
    j_06          ,  // [ 86] M3    ISP:J06
    j_05          ,  // [ 85] L3    ISP:J05
    j_04          ,  // [ 84] J3    ISP:J04
    j_03          ,  // [ 83] H4    ISP:J03
    j_02          ,  // [ 82] H3    ISP:J02
    zif_48        ,  // [ 81] T12   ZIF48
    zif_47        ,  // [ 80] R12   ZIF47
    zif_46        ,  // [ 79] T14   ZIF46
    zif_45        ,  // [ 78] R14   ZIF45
    zif_44        ,  // [ 77] T15   ZIF44
    zif_43        ,  // [ 76] R16   ZIF43
    zif_42        ,  // [ 75] P15   ZIF42
    zif_41        ,  // [ 74] N16   ZIF41
    zif_40        ,  // [ 73] N14   ZIF40
    zif_39        ,  // [ 72] K16   ZIF39
    zif_38        ,  // [ 71] J16   ZIF38
    zif_37        ,  // [ 70] J14   ZIF37
    zif_36        ,  // [ 69] J1    ZIF36
    zif_35        ,  // [ 68] H2    ZIF35
    zif_34        ,  // [ 67] H1    ZIF34
    zif_33        ,  // [ 66] K2    ZIF33
    zif_32        ,  // [ 65] M2    ZIF32
    zif_31        ,  // [ 64] M1    ZIF31
    zif_30        ,  // [ 63] N1    ZIF30
    zif_29        ,  // [ 62] N3    ZIF29
    zif_28        ,  // [ 61] P1    ZIF28
    zif_27        ,  // [ 60] P2    ZIF27
    zif_26        ,  // [ 59] R1    ZIF26
    zif_25        ,  // [ 58] R2    ZIF25
    zif_24        ,  // [ 57] A3    ZIF24
    zif_23        ,  // [ 56] B3    ZIF23
    zif_22        ,  // [ 55] A2    ZIF22
    zif_21        ,  // [ 54] B2    ZIF21
    zif_20        ,  // [ 53] B1    ZIF20
    zif_19        ,  // [ 52] C1    ZIF19
    zif_18        ,  // [ 51] D1    ZIF18
    zif_17        ,  // [ 50] E1    ZIF17
    zif_16        ,  // [ 49] E2    ZIF16
    zif_15        ,  // [ 48] F1    ZIF15
    zif_14        ,  // [ 47] G1    ZIF14
    zif_13        ,  // [ 46] F2    ZIF13
    zif_12        ,  // [ 45] H16   ZIF12
    zif_11        ,  // [ 44] H15   ZIF11
    zif_10        ,  // [ 43] G16   ZIF10
    zif_09        ,  // [ 42] G14   ZIF09
    zif_08        ,  // [ 41] F16   ZIF08
    zif_07        ,  // [ 40] F15   ZIF07
    zif_06        ,  // [ 39] E16   ZIF06
    zif_05        ,  // [ 38] D16   ZIF05
    zif_04        ,  // [ 37] C16   ZIF04
    zif_03        ,  // [ 36] C15   ZIF03
    zif_02        ,  // [ 35] B16   ZIF02
    zif_01        ,  // [ 34] B15   ZIF01
    unknown_c4    ,  // [ 33] C4    ? ro5 ?
    m1            ,  // [ 32] N11   M1
    m0            ,  // [ 31] T11   M0
    cpu_p13       ,  // [ 30] R5    Cpu: 13
    HTVLD         ,  // [ 29] C11   Cpu: 52
    HTREQ         ,  // [ 28] C9    Cpu: 54
    HTCLK         ,  // [ 27] E8    Cpu: 56
    HTACK         ,  // [ 26] C8    Cpu: 55
    HRVLD         ,  // [ 25] L7    Cpu: 14
    HRCLK         ,  // [ 24] R7    Cpu: 10
    HRACT         ,  // [ 23] T5    Cpu: 11
    HD9           ,  // [ 22] D5    Cpu: 25
    HD8           ,  // [ 21] D8    Cpu: 24
    HD7           ,  // [ 20] M9    Cpu:23
    HD6           ,  // [ 19] P10   Cpu: 22
    HD5           ,  // [ 18] N12   Cpu: 21
    HD4           ,  // [ 17] P12   Cpu: 20
    HD31          ,  // [ 16] T10   Cpu: 51
    HD3           ,  // [ 15] N5    Cpu: 19
    HD22          ,  // [ 14] B5    Cpu: 38
    HD21          ,  // [ 13] A4    Cpu: 37
    HD20          ,  // [ 12] C7    Cpu: 36
    HD2           ,  // [ 11] C10   Cpu: 53
    HD19          ,  // [ 10] R11   Cpu: 35
    HD18          ,  // [  9] R3    Cpu: 34
    HD16          ,  // [  8] P13   Cpu: 32
    HD15          ,  // [  7] A7    Cpu: 31
    HD14          ,  // [  6] E7    Cpu: 30
    HD13          ,  // [  5] E6    Cpu: 29
    HD12          ,  // [  4] C6    Cpu: 28
    HD11          ,  // [  3] D6    Cpu: 27
    HD10          ,  // [  2] C5    Cpu: 26
    HD1           ,  // [  1] P5    Cpu: 17
    HD0             // [  0] L8    Cpu: 15
};
